# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  microservices01apitest:
    image: microservices01apitest
    build:
      context: .
      dockerfile: Microservices01.Api.Test/Dockerfile
    ports:
      - 5161:5161
